---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS2
  region: us-west-2
  version: '1.19'

iam:
  withOIDC: true

ManagedNodeGroups:
  - name: EKS2
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmamzonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
       withAddonPolicies:
         externalDNS: true
         certManager: true
    ssh:
        allow: true
        publicKeyPath: ~/.ssh/Oregon-Key.pem
        enableSsm: true

    labels: {role: worker}
    tags:
      nodegroup-role: worker   